### PR TITLE
Add Google search console verification

### PR DESCRIPTION
**Pull request by miike**

### CODE REVIEW

**Comment by mattodd** [comment]
Hi @miike - is this fixing something?

**Comment by miike** [comment]
Yep - this basically adds a verification file to the opensourcemalaria.github.io domain that shows ownership so that it can be registered in Search Console ( https://search.google.com/search-console/about ). I'm using this as a test to see if this works around the Google indexing issues in Google Docs by mirroring the sheet on this domain (related to https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/54#issuecomment-788236868 )

**Comment by miike** [comment]
Alright - the good news is Google now seems to be indexing this mirrored page. It wasn't very happy to index the iframe but was fine if I embed the structures themselves - so I'll need to figure out an update mechanism for this long term. I don't think Google does a great job of extract string matching here (probably due to some metacharacters) but I suspect it'll do much better on InChI / InChI keys.

Example SMILES string (rank will vary but it should be on the first page): https://www.google.com/search?q=%22O%3DS(CCN1CC2%3DCC%3DNC%3DC2)(CC1)%3DO%22&oq=%22O%3DS(CCN1CC2%3DCC%3DNC%3DC2)(CC1)%3DO%22&aqs=chrome..69i57.658j0j7&sourceid=chrome&ie=UTF-8

https://www.google.com/search?q=%22CN1CCN(CC1)c1ccc(cc1)C%23N%22&oq=%22CN1CCN(CC1)c1ccc(cc1)C%23N%22&aqs=chrome.0.69i59l2.851j0j7&sourceid=chrome&ie=UTF-8

cc @drc007

**Comment by drc007** [comment]
Very nice

**Pull request merged**
